jobs:
  include:
    - stage: test
      sudo: false
      language: javascript
      install: npm install
      script: npm run test:lint:js && npm run test:unit:js && npm run test:smoke:typescript
    - stage: build android
      language: android
      sudo: false
      android:
        components:
         - tools
         - platform-tools
         - build-tools-26.0.2
         - android-26
         - extra-google-m2repository
         - extra-android-m2repository
      env:
        - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a
        - ADB-INSTALL_TIMEOUT=5
      before_install:
        - yes | sdkmanager "platforms;android-26"
        - yes | sdkmanager "platforms;android-23"
      install:
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
      before_script:
        - npm install
        - npm install babel-cli
        - PATH="node_modules/bin:$PATH" && npm pack
      script:
        - cd examples/plain
        - yarn add ../../bugsnag-react-native-*.tgz
        - yarn install
        - ./node_modules/.bin/react-native link
        - cd android
        - ./gradlew assembleRelease
      licenses:
        -
    - stage: build cocoa
      language: objective-c
      osx-image: xcode9.2
      env: SDK=macosx10.12 BUILD_OSX=9
      xcode_project: ./cocoa/BugsnagReactNative.xcodeproj
      xcode_scheme: BugsnagReactNative
      install:
        - brew install node yarn
      before_script:
        - npm install
        - npm install babel-cli
        - PATH="node_modules/bin:$PATH" && npm pack
      script:
        - cd examples/plain
        - yarn add ../../bugsnag-react-native-*.tgz
        - yarn install
        - ./node_modules/.bin/react-native link
        - cd ios
        - xcodebuild -project BugsnagReactNativeExample.xcodeproj -scheme BugsnagReactNativeExample build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -quiet
